{
 "title": "Gitploy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "gitploy_deployment_count" } },
   { "name": "name", "label": "Name", "query": { "query": "gitploy_deployment_count" } }
  ]
 },
 "panels": [
  { "title": "Deployment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# Deployment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg(gitploy_deployment_count{namespace=~\"$namespace\",name=~\"$name\"}) by (namespace, name)",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "# Deployment per a day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "avg(gitploy_deployment_count{namespace=~\"$namespace\",name=~\"$name\"}) by (namespace, name)\n- avg((gitploy_deployment_count{namespace=~\"$namespace\",name=~\"$name\"} offset 1d)) by (namespace, name)",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  },
  {
   "title": "# Deployment per a week",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "avg(gitploy_deployment_count{namespace=~\"$namespace\",name=~\"$name\"}) by (namespace, name)\n- avg((gitploy_deployment_count{namespace=~\"$namespace\",name=~\"$name\"} offset 1w)) by (namespace, name)",
     "legendFormat": "{{namespace}}/{{name}}"
    }
   ]
  }
 ]
}